export const TERMINAL_TASK_BAR = ['SUCCESS', 'ERROR', 'CANCELLED', 'STALE'];

export const TASK_BAR_STATUS = {
  RECEIVED: 'RECEIVED',
  SUCCESS: 'SUCCESS',
  ERROR: 'ERROR',
  CANCELLED: 'CANCELLED',
  STALE: 'STALE',
};

/** Default poll interval for active mutationLogs entries (ms). */
export const TASK_BAR_POLL_INTERVAL_MS = 2500;

/** Force-stop polling for status=0 entries older than this (ms). */
export const TASK_BAR_STALE_TIMEOUT_MS = 30 * 60 * 1000;

export const MUTATION_LOG_TASKBAR_PROJECTION = [
  'id',
  'clientMutationId',
  'clientMutationLabel',
  'requestDateTime',
  'status',
  'error',
  'taskBarStatus',
  'shouldStopPolling',
  'taskBarMessage',
  'clientMutationDetails',
  'jsonExt',
  'autogeneratedCode',
];

/**
 * Stop polling mutationLogs for this clientMutationId.
 */
export function shouldStopMutationPolling(node) {
  if (!node) return true;
  if (node.shouldStopPolling === true) return true;
  if (node.taskBarStatus === TASK_BAR_STATUS.SUCCESS) return true;
  if (node.taskBarStatus && TERMINAL_TASK_BAR.includes(node.taskBarStatus)) {
    return true;
  }
  // Legacy numeric status only when taskBarStatus is absent (indexation OS peut garder status=0).
  if (!node.taskBarStatus && (node.status === 1 || node.status === 2)) {
    return true;
  }
  return false;
}

export function getEffectiveTaskBarStatus(node) {
  if (!node) return null;
  if (node.taskBarStatus) return node.taskBarStatus;
  if (node.status === 1) return TASK_BAR_STATUS.ERROR;
  if (node.status === 2) return TASK_BAR_STATUS.SUCCESS;
  if (node.status === 0) return TASK_BAR_STATUS.RECEIVED;
  return null;
}

export function isMutationActive(node, now = Date.now()) {
  return isTaskBarSpinnerVisible(node);
}

/** Spinner : RECEIVED tant que shouldStopPolling est false et pas SUCCESS. */
export function isTaskBarSpinnerVisible(node) {
  if (!node?.clientMutationId) return false;
  if (shouldStopMutationPolling(node)) return false;
  const effective = getEffectiveTaskBarStatus(node);
  if (effective === TASK_BAR_STATUS.RECEIVED) return true;
  return effective == null && node.status === 0 && node.shouldStopPolling !== true;
}

export function isMutationStaleWithoutStop(node, now = Date.now()) {
  if (!node || node.status !== 0 || shouldStopMutationPolling(node)) return false;
  if (!node.requestDateTime) return false;
  const started = new Date(node.requestDateTime).getTime();
  if (Number.isNaN(started)) return false;
  return now - started > TASK_BAR_STALE_TIMEOUT_MS;
}

/**
 * Merge GraphQL mutation log node into store entry.
 */
export function mergeMutationLogNode(existing, node) {
  if (!node) return existing;
  const merged = {
    ...existing,
    ...node,
    id: node.id ?? existing?.id,
    clientMutationId: node.clientMutationId ?? existing?.clientMutationId,
    clientMutationLabel: node.clientMutationLabel ?? existing?.clientMutationLabel,
    requestDateTime: node.requestDateTime ?? existing?.requestDateTime,
    status: node.status != null ? node.status : existing?.status,
    error: node.error ?? existing?.error,
    taskBarStatus: node.taskBarStatus ?? existing?.taskBarStatus,
    shouldStopPolling: node.shouldStopPolling ?? existing?.shouldStopPolling,
    taskBarMessage: node.taskBarMessage ?? existing?.taskBarMessage,
    clientMutationDetails: node.clientMutationDetails ?? existing?.clientMutationDetails,
    jsonExt: node.jsonExt ?? existing?.jsonExt,
  };
  if (merged.taskBarStatus && TERMINAL_TASK_BAR.includes(merged.taskBarStatus)) {
    if (merged.taskBarStatus === TASK_BAR_STATUS.SUCCESS) {
      merged.status = 2;
    } else if (merged.taskBarStatus === TASK_BAR_STATUS.ERROR) {
      merged.status = 1;
    }
  }
  return merged;
}
